@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class PaymentController {
  + PaymentController(): 
  ~ settingService: SettingService
  ~ paymentService: PaymentService
  ~ paymentDao: PaymentDao
  ~ userDao: UserDao
  ~ rewardDao: RewardDao
  ~ rewardService: RewardService
  ~ projectDao: ProjectDao
  ~ projectService: ProjectService
}
interface PaymentDao << interface >>
class PaymentDaoImpl {
  + PaymentDaoImpl(): 
  ~ projectDto: ProjectDto
  ~ projectDao: ProjectDao
  ~ paymentDto: PaymentDto
  - namespace: String
  - session: SqlSession
  ~ userDto: UserDto
}
class PaymentDto {
  + PaymentDto(): 
  + PaymentDto(Integer, Date, int, int, int, int, int, String, String, String, String, String, String, int, String, int, int, int): 
  - prdt_id: int
  - delivery_postcode: String
  - pay_carddate: int
  - pay_no: Integer
  - delivery_addressdetail: String
  - delivery_phone: String
  - pay_time: Date
  - delivery_reciever: String
  - user_no: int
  - delivery_memo: String
  - pay_total: int
  - pay_pwd: int
  - reward_user_cnt: int
  - reward_id: int
  - delivery_address: String
  - pay_cardnum: String
  - pay_cvc: int
  - delivery_charge: int
}
interface PaymentService << interface >>
class PaymentServiceImpl {
  + PaymentServiceImpl(): 
  ~ paymentDao: PaymentDao
}
interface ProjectDao << interface >>
class ProjectDaoImpl {
  + ProjectDaoImpl(): 
  - namespace: String
  ~ projectDto: ProjectDto
  - session: SqlSession
}
class ProjectDto {
  + ProjectDto(String, Integer, String, String, String, Date, Date, Date, int, int, boolean, String, Integer, String, String, int, int, int, Date, Date, int, String, String, String, int, Date, String, String, int, int, int): 
  + ProjectDto(): 
  - prdt_user_no: int
  - user_role: String
  - prdt_open: boolean
  - prdt_desc_detail: String
  - prdt_limitday: Date
  - prdt_enddate: Date
  - user_id: String
  - user_regdate: Date
  - user_phone: int
  - prdt_desc: String
  - prdt_desc_policy: String
  - prdt_thumbnail: String
  - prdt_dday: int
  - prdt_currenttotal: int
  - prdt_regdate: Date
  - prdt_comingday: int
  - prdt_percent: int
  - user_no: int
  - writer: String
  - prdt_buyercnt: int
  - prdt_name: String
  - user_activate: String
  - pay_no: int
  - prdt_genre: Integer
  - prdt_img: String
  - user_name: String
  - user_pwd: String
  - prdt_opendate: Date
  - prdt_purchaseday: Date
  - prdt_id: Integer
  - prdt_goal: int
}
interface ProjectService << interface >>
class ProjectServiceImpl {
  + ProjectServiceImpl(): 
  ~ projectDao: ProjectDao
}
interface RewardDao << interface >>
class RewardDaoImpl {
  + RewardDaoImpl(): 
  - session: SqlSession
  - namespace: String
}
class RewardDto {
  + RewardDto(int, int, String, String, int, int, int, int, int, int, int): 
  + RewardDto(): 
  - user_no: int
  - reward_id: int
  - reward_price: int
  - reward_category: int
  - row_number: int
  - reward_stock: int
  - reward_name: String
  ~ paymentDto: PaymentDto
  - reward_desc: String
  - pay_no: int
  - prdt_id: int
  - reward_user_cnt: int
  - reward_cnt: int
}
interface RewardService << interface >>
class RewardServiceImpl {
  + RewardServiceImpl(): 
  ~ rewardDao: RewardDao
}
interface UserDao << interface >>
class UserDaoImpl {
  + UserDaoImpl(): 
  - session: SqlSession
  - namespace: String
}
class UserDto {
  + UserDto(): 
  + UserDto(int, String, String, int): 
  - user_pwd: String
  - user_id: String
  - user_profile: String
  - user_role: int
  - user_phone: String
  - user_no: int
  - user_activate: int
  - user_name: String
  - user_regdate: Date
}

PaymentDaoImpl      -[#008200,dashed]-^  PaymentDao         
PaymentServiceImpl  -[#008200,dashed]-^  PaymentService     
ProjectDaoImpl      -[#008200,dashed]-^  ProjectDao         
ProjectServiceImpl  -[#008200,dashed]-^  ProjectService     
RewardDaoImpl       -[#008200,dashed]-^  RewardDao          
RewardServiceImpl   -[#008200,dashed]-^  RewardService      
UserDaoImpl         -[#008200,dashed]-^  UserDao            
@enduml
