@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class CommunityController {
  + CommunityController(): 
  ~ service: CommunityService
}
interface CommunityDao << interface >>
class CommunityDaoImpl {
  + CommunityDaoImpl(): 
  - namespace: String
  - session: SqlSession
}
class CommunityDto {
  + CommunityDto(): 
  + CommunityDto(String, String): 
  - chat_no: int
  - chat_context: String
  - user_no: int
  - chat_date: Date
  - prdt_id: int
  - chat_type: int
  - chat_writer: String
}
interface CommunityService << interface >>
class CommunityServiceImpl {
  + CommunityServiceImpl(CommunityDao, BoardDao): 
  ~ communityDao: CommunityDao
  ~ boardDao: BoardDao
}
class ReplyController {
  + ReplyController(): 
  ~ replyService: ReplyService
}
interface ReplyDao << interface >>
class ReplyDaoImpl {
  + ReplyDaoImpl(): 
  - namespace: String
  - session: SqlSession
}
class ReplyDto {
  + ReplyDto(): 
  - chat_context: String
  - prdt_id: int
  - rno: int
  - chat_no: int
  - chat_date: Date
  - user_no: int
  - chat_writer: String
}
interface ReplyService << interface >>
class ReplyServiceImpl {
  + ReplyServiceImpl(): 
  ~ replyDao: ReplyDao
}

CommunityDaoImpl      -[#008200,dashed]-^  CommunityDao         
CommunityServiceImpl  -[#008200,dashed]-^  CommunityService     
ReplyDaoImpl          -[#008200,dashed]-^  ReplyDao             
ReplyServiceImpl      -[#008200,dashed]-^  ReplyService         
@enduml
