@startuml
actor User
participant "Web Client" as C
participant "Purplaying Server" as S
database "Purplaying DB" as D

User -> C : 인기펀딩 페이지 GET(/purplaying/popularFunding)
activate C
C -> S : static asset(HTML,CSS,JS) 요청
activate S
S -> D : 인기펀딩 요청
activate D
D --> S : Select 인기펀딩(달성률) 상위 6개 응답
deactivate D
S --> C : static asset(HTML,CSS,JS) 응답
deactivate S
C --> User : 인기펀딩 페이지 노출
deactivate C

@enduml