@startuml

header purplaying sequence
footer Page %page% of %lastpage%


actor User
participant "Web Client" as C
participant "Purplaying Server" as S
database "Project DB" as DB_prj
database "File DB" as DB_file
database "Reward DB" as DB_rwd

title 신규프로젝트 작성

'프로젝트 작성
User -> C: 1.신규프로젝트 작성버튼 클릭\nGET: [/purplaying/project/write]

activate C
C -> S: 작성 안내페이지 요청\n(HTML/CSS 등)
S -->C: 작성 안내페이지 응답\n(HTML/CSS 등)
C --> User: 작성 안내페이지 출력\n[projectRegisterIntro.jsp]
deactivate C

User -> C: 2.프로젝트 작성 시작버튼 클릭\nPOST: [/purplaying/project/write]
activate C
C -> S: 프로젝트 작성페이지 요청\n(HTML/CSS 등)

activate S
S -> S : 세션 로그인 id 확인\n비회원이면 로그인화면 redirection
S -> DB_prj: 프로젝트 DB 기본데이터\n(id,작성자,날짜,목표금액 등) insert 요청
DB_prj --> S: 프로젝트 DB 기본데이터\n(id,작성자,날짜,목표금액 등) insert 응답
S --> C : 프로젝트 작성페이지 응답
deactivate S

C --> User: 프로젝트 작성페이지 출력\n[projectRegisterPage.jsp]
deactivate C


'프로젝트 대표 이미지 업로드
User -> C: 3.프로젝트 대표 이미지 파일\nUpload 버튼 클릭\nPOST: [/purplaying/file/upload]

activate C
C -> S: 프로젝트 대표 이미지\n(썸네일) 요청

activate S
S -> S: 파일 확장자 확인\n(이미지 파일 유효성 검사)
S -> S: 파일 용량 확인\n(용량 제한 유효성 검사)
S -> S: 파일명(UUID), 파일 저장경로 생성\n(원본,썸네일 2가지 생성)
S ->DB_file: 이미지 파일 DB insert 요청
DB_file --> S : 이미지 파일 DB insert 응답
S --> C : 파일명, 경로 return\n(원본,썸네일)
deactivate S

C --> User: 프로젝트 대표 이미지\n(썸네일) 출력
deactivate C


'리워드 작성
User -> C: 4.리워드 추가하기 버튼 클릭\nPOST: [/purplaying/pr/reward]

activate C
C -> S: 리워드 미리보기\n(HTML/CSS) 출력 요청
activate S
S -> DB_rwd: 리워드 DB insert 요청
DB_rwd --> S :리워드 DB insert 응답
S -->C: 리워드 미리보기\n(HTML/CSS) 출력 응답
deactivate S
C --> User: 리워드 미리보기 출력
deactivate C

newpage

'수정
User -> C: 5.프로젝트 저장버튼 클릭\nPATCH: [/purplaying/project/modify/{프로젝트id}]

activate C
C -> S: 프로젝트 저장 요청 

activate S
S -> DB_prj: 프로젝트 DB update 요청
DB_prj --> S :프로젝트 DB update 응답
S ->DB_file: 이미지 파일 DB insert 요청
DB_file --> S : 이미지 파일 DB insert 응답
S -> DB_rwd: 리워드 DB update 요청
DB_rwd --> S :리워드 DB update 응답
S --> C : 프로젝트 저장 응답
deactivate S

C --> User: 프로젝트 저장 완료
deactivate C

'미리보기
User -> C: 6.프로젝트 미리보기버튼 클릭\nGET: [/purplaying/project/view/{프로젝트id}]

activate C
C -> S: 작성중인 프로젝트 저장 요청 

activate S
S -> DB_prj: 프로젝트 DB update 요청
DB_prj --> S :프로젝트 DB update 응답
S ->DB_file: 이미지 파일 DB insert 요청
DB_file --> S : 이미지 파일 DB insert 응답
S -> DB_rwd: 리워드 DB update 요청
DB_rwd --> S :리워드 DB update 응답
S --> C : 프로젝트 저장 응답
C -> S: 작성중인 프로젝트 미리보기 요청 
S --> C: 작성중인 프로젝트 미리보기 응답
deactivate S

C --> User: 프로젝트 저장 완료,\n미리보기페이지로 이동
deactivate C

'삭제
User -> C: 6.프로젝트 삭제버튼 클릭\nDELETE: [/purplaying/project/remove/{프로젝트id}]

activate C
C -> S: 프로젝트 삭제 요청 

activate S
S -> DB_prj: 프로젝트 DB delete 요청
DB_prj --> S :프로젝트 DB delete 응답
S ->DB_file: 이미지 파일 DB delete 요청
DB_file --> S : 이미지 파일 DB delete 응답
S -> DB_rwd: 리워드 DB delete 요청
DB_rwd --> S :리워드 DB delete 응답
S --> C : 프로젝트 삭제 응답
deactivate S

C --> User: 프로젝트 삭제 완료,\n마이페이지로 이동
deactivate C


@enduml