@startuml

actor User
actor Admin
participant "Web Client" as C
participant "Purplaying Server" as S
database "Purplaying DB" as D

' 문의사항 리스트
User -> C: 문의사항 리스트 GET [/purplaying/oneonone/list]
activate C
C -> S: static asset 요청(HTML/CSS 등)
activate S
S --> C: HTML/CSS 등 응답
deactivate S
C -> C: 0. 로그인이 되어 있지 않을 경우 로그인 페이지로 redirection
C --> User: 로그인 입력 페이지 [/purplaying/user/login]

User -> C: 1. 아이디/Pw 입력 
C -> C: cookie에 아이디 저장 
C -> C: 문의사항 리스트 페이지로 redirection GET [/purplaying/oneonone/list]

activate S
S -> D: 문의사항 list 총 게시글 수 요청
D --> S :문의사항 list 총 게시글 수 응답
S --> C : HTML/CSS 응답
deactivate S

C --> User: 문의 게시판 리스트 페이지

' 문의사항 게시판 읽기
User -> C: 2.문의사항 게시글 읽기 GET: [/purplaying/oneonone/read]

C -> S: static asset 요청(HTML/CSS 등)

activate S
S -> D: 문의사항 게시글 select
D --> S :문의사항 게시글 select
S --> C : HTML/CSS 응답
deactivate S

C --> User: 문의사항 게시글 출력

' 문의 사항 작성
User -> C: 3. 작성 버튼 선택 GET [/purplaying/oneonone/write]

C -> S: 작성 폼 요청(HTML/CSS 등)
activate S
S --> C: 작성 폼 응답
deactivate S

User -> C: 문의사항 게시글 작성 POST [/purplaying/oneonone/write/reg]

C -> C: 작성 폼 출력
C -> C: 작성 확인 선택

S -> D: 문의글 DB insert 요청
D --> S: 문의글 DB insert 응답
C -> C: 문의글 리스트 페이지로 redirection
C --> User: 문의글 리스트 페이지 노출


'문의사항 수정
User -> C: 4. 문의사항 게시글 수정버튼 클릭 GET [/purplaying/oneonone/modify]

C -> S: 수정페이지 요청(HTML/CSS 등)
activate S
S -> S: 세션아이디와 작성자아이디 일치확인
S -->C: 수정페이지 응답(HTML/CSS 등)
deactivate S
C --> User: 문의사항 수정페이지 출력

User -> C: 문의사항 게시글 수정 POST [/purplaying/oneonone/modify]
C -> S: 게시글 수정 요청 
S -> D: 문의사항 게시글 DB update 요청
D --> S :문의사항 게시글 DB update 응답
S --> C : 게시글 수정 응답

C --> User: 문의사항 게시글 수정완료,리스트로 이동

'문의사항 삭제
User -> C: 5. 문의사항 게시글 삭제버튼 클릭 POST [/purplaying/oneonone/remove]

C -> S: 게시글 삭제 요청
activate S
S -> S: 세션아이디와 작성자아이디 일치 OR 관리자 권한 확인
S -> D: 문의사항 게시글 DB delete 요청
D --> S : 문의사항 게시글 DB delete 응답
S -->C: 게시글 삭제 응답
deactivate S
C --> User: 문의사항 게시글 삭제 완료 리스트로 이동

' 문의 사항 답변 작성
Admin -> Admin : 관리자에게만 답변 버튼 활성화
Admin -> C: 6. 답변 작성 버튼 선택 

C -> S: 답변 작성 폼 요청(HTML/CSS 등)
activate S
S --> C: 답변 작성 폼 응답
deactivate S

Admin -> C: 문의사항 답변 게시글 작성 POST [/purplaying/oneonone/write/ans]

C -> C: 답변 작성 폼 출력
C -> C: 답변 작성 확인 선택

S -> D: 문의 답변글 DB insert 요청
D --> S: 문의 답변글 DB insert 응답
C -> C: 답변 중 -> 답변 완료로 변경
C -> C: 문의글 페이지로 redirection
C --> Admin: 문의글 페이지 노출


'문의사항 답변 수정
Admin -> C: 7. 문의사항 답변 게시글 수정버튼 클릭 GET [/purplaying/oneonone/modify/ans]

C -> S: 수정페이지 요청(HTML/CSS 등)
activate S
S -> S: 세션아이디와 작성자아이디 일치확인
S -->C: 수정페이지 응답(HTML/CSS 등)
deactivate S
C --> Admin: 문의사항 답변 수정페이지 출력

Admin -> C: 문의사항 답변 수정 POST [/purplaying/oneonone/modify]
C -> S: 답변 수정 요청 
S -> D: 문의사항 답변 DB update 요청
D --> S :문의사항 답변 DB update 응답
S --> C : 답변 수정 응답

C --> Admin: 문의사항 답변 수정완료,게시글로 이동

'문의사항 답변 삭제
Admin -> C: 7. 문의사항 답변 삭제버튼 클릭 POST [/purplaying/oneonone/remove/ans]

C -> S: 답변 삭제 요청
activate S
S -> S: 세션아이디 관리자 권한 확인
S -> D: 문의사항 답변 DB delete 요청
D --> S : 문의사항 답변 DB delete 응답
S -->C: 답변 삭제 응답
deactivate S
C --> Admin: 문의사항 답변 삭제 완료 리스트로 이동



loop
    User -> C: 문의글 작성 & 수정 & 삭제
    C -> C: 게시판 작성/수정/삭제 버튼 선택
    S -> D: 문의글 DB insert/update/delete 요청
    D --> S: 문의글 DB insert/update/delete 응답
    C -> C: 문의글 리스트 페이지로 redirection
    C --> User: 문의글 리스트 페이지 노출
    Admin -> C: 답변 작성 & 수정 & 삭제
    C -> C: 답변 작성/수정/삭제 버튼 선택
    S -> D: 답변글 DB insert/update/delete 요청
    D --> S: 답변글 DB insert/update/delete 응답
    C -> C: 문의물 OR 리스트 페이지로 redirection
    C --> Admin: 문의글 페이지 노출 OR delete시 리스트 페이지 노출
end

deactivate C

@enduml