@startuml

actor User
participant "Web Client" as C
participant "Purplaying Server" as S
database "DBMS Server" as D

group 회원탈퇴
    User -> C:회원탈퇴페이지 요청\nGET:[/purplaying/user/leave]

    activate C
    C -> S:static asset 요청(HTML/CSS)
    activate S
    S --> C: static asset 응답(HTML/CSS)
    deactivate S
    C --> User: 회원탈퇴 페이지 출력
 
    alt 1대1문의 버튼 선택
        User -> C:1대1문의페이지 요청\nGET:[/purplaying/oneonone/list]
        C -> S:static asset 요청(HTML/CSS)
        activate S
        S --> C: static asset 응답(HTML/CSS)
        deactivate S
        C --> User:1대1문의페이지 출력
    else 회원탈퇴 진행
        C -> C:탈퇴 유의사항 버튼 선택
        C -> C:탈퇴사유 선택및 사유 입력
        C -> C:본인인증 버튼 선택
        C --> User: 탈퇴 본인인증 Modal노출

        User -> C: 비밀번호 입력
        C -> S:회원탈퇴 요청
        activate S
        S -> D:회원 activate Update 요청
        D --> S:회원 activate Update 응답
        S -> C:회원탈퇴 응답
        deactivate S
        C -> C:메인페이지 redirection
        C --> User:메인페이지 노출
        deactivate C
    end
end

@enduml