@startuml Community
participant User
participant "Web Client" as C
participant "Purplaying Server" as S
participant "Purplaying DB" as D

User -> C: 1. 탭 메뉴 커뮤니티 선택
activate C
C -> S: static asset 요청(HTML/CSS 등)
activate S
S -> D: 커뮤니티 DB select 요청
D --> S: 커뮤니티 DB select 응답
S --> C: HTML/CSS 등 응답
deactivate S
C -> C: 커뮤니티 댓글 폼 및 리스트 출력
C -> C: 커뮤니티 댓글 리스트 페이지로 redirection
C --> User: 커뮤니티 댓글 리스트 페이지 노출

loop
  User -> C: 2. 커뮤니티 댓글 작성 & 추가
  C -> C: 커뮤니티 댓글 작성 버튼 선택
  S -> D: 커뮤니티 댓글 DB insert 요청
  D --> S: 커뮤니티 댓글 DB insert 응답
  C -> C: 커뮤니티 댓글 리스트 페이지로 redirection
  C --> User: 커뮤니티 댓글 리스트 페이지 노출
end

deactivate C

@enduml