@startuml
actor User
participant "Web Client" as C
participant "Purplaying Server" as S
database "Purplaying DB" as D

User -> C : 최신펀딩 페이지 GET(/purplaying/newFunding)
activate C
C -> S : static asset(HTML,CSS,JS) 요청
activate S
S -> D : 최신펀딩 요청
activate D
D --> S : Select 최신펀딩(오픈일) 상위 6개 응답
deactivate D
S --> C : static asset(HTML,CSS,JS) 응답
deactivate S
C --> User : 최신펀딩 페이지 노출
deactivate C

@enduml