@startuml

actor User
participant "Web Client" as C
participant "Purplaying Server" as S
database "Purplaying DB" as D

group 마이페이지(펀딩현황)
    User -> C:마이페이지(유저권한) 요청\nGET:[/purplaying/mypage]

    activate C
    C -> S:static asset 요청(HTML/CSS)
    activate S

    S -> D: 펀딩작성내역, 후원내역 요청
    D --> S: 펀딩작성내역, 후원내역 응답

    S --> C: static asset 응답(HTML/CSS)
    deactivate S

    C --> User:펀딩현황 페이지 출력

    deactivate C

end



@enduml