@startuml

actor User
participant "Web Client" as C
participant "Purplaying Server" as S
database "Purplaying DB" as D

group 마이페이지(관심펀딩)
    User -> C:마이페이지(유저권한) 요청\nGET:[/purplaying/mypage]

    activate C
    C -> S:static asset 요청(HTML/CSS)
    activate S

    S -> D: 관심펀딩 DB 중,\n오픈일 or 종료일 D-1 select 요청
    D --> S: 관심펀딩 DB 중,\n오픈일 or 종료일 D-1 select 응답

    S --> C: static asset 응답(HTML/CSS)
    deactivate S

    C --> User:펀딩알림 페이지 출력

    alt
        User -> C: 펀딩별 알림 [확인] 클릭
        C -> S: static asset 요청(HTML/CSS)
        S -> D: 조회수=+1 요청
        D --> S : 조회수=+1 응답
        S --> C: static asset 응답(HTML/CSS)
        C --> User: 펀딩 목록 재정렬\n(확인된 펀딩 아래로)
    else
        User -> C: 관심 버튼 선택
        C -> S: 관심 해제 요청
        activate S
        S -> D: 관심, 알림 Delete요청
        D --> S: 관심, 알림 Delete응답 
        S --> C: 관심 해제 응답
        deactivate S
        
        C -> C : 관심펀딩 페이지 redirection
        C --> User: 관심펀딩 페이지 출력
        deactivate C

        
        
    end
end



@enduml