@startuml
actor User
participant "Web Client" as C
participant "Purplaying Server" as S
database "DBMS Server" as D
participant "SMTP" as M

User -> C:3. 아이디 찾기 페이지 요청\nGET:[/purplaying/user/findaccount]


activate C
C -> S:static asset 요청(HTML/CSS)
activate S
S --> C: static asset 응답(HTML/CSS)
deactivate S

group 아이디 찾기
    User -> C:이름,전화번호 입력

    C -> S:이름,전화번호일치 아이디 요청
    activate S
    S -> D:아이디 DB select요청
    D --> S:아이디 DB select응답
    S --> C:이름,전화번호일치 아이디 응답
    deactivate S

    alt 아이디 존재
        C --> C: 로그인페이지 redirection
        C --> User:로그인페이지 노출

    else 아이디 미존재
        C --> C: 회원가입페이지 redirection
        C --> User:회원가입페이지 노출
        deactivate C
    end
end
    
group 비밀번호 찾기
    User -> C:아이디 입력
    activate C
    C -> S:이메일 전송요청

    activate S
    S -> M:임시비밀번호(난수) 이메일 전송
    S -> D:임시비밀번호(난수) insert요청
    D --> S:임시비밀번호(난수) insert응답

    alt 비밀번호 보러가기 버튼
        S --> C: 전송된 이메일 사이트 탭생성

    else 로그인 하러가기 버튼
        S --> C:로그인페이지 redirection
        deactivate S
    end

    C --> User: 로그인페이지 노출
    deactivate C

end

@enduml