@startuml
actor User as U
participant "Web Client" as C
participant "Purplaying Server" as S
database "Purplaying DB" as D

U -> C: 배송지탭 버튼 입력
activate C
C -> S : static asset(HTML,CSS,JS) 요청
activate S
S -> D : 유저 배송지 목록 요청
activate D
D --> S : select user_no = {user_no}에 해당하는 유저 배송지 목록 응답
deactivate D
S --> C : static asset(HTML,CSS,JS) 응답
deactivate S
C --> U : 배송지탭 활성화
deactivate C

U -> C : 배송지 추가 버튼 입력
activate C
alt 배송지가 >= 3
C --> U : alert 호출
else 배송지 갯수 < 3
C -> S : static asset(HTML,CSS,JS) 요청
activate S
S --> C : static asset(HTML,CSS,JS) 응답
deactivate S
C --> U : 배송지 추가 모달 활성화
U -> C : 배송지 정보 입력 및 배송지 추가 완료 버튼 입력
C -> S : static asset(HTML,CSS,JS) 요청
activate S
S --> D : 배송지 추가 정보 전달
activate D
D --> S : select user_no = {user_no}에 해당하는 유저 배송지 목록 응답
deactivate D
S --> C : static asset(HTML,CSS,JS) 응답
deactivate S
C --> U : 배송지 추가 모달 비활성화 및 배송지 목록 출력
deactivate C
end

U -> C : 배송지 수정 버튼 입력
activate C
C -> S : static asset(HTML,CSS,JS) 요청
activate S
S --> D : 배송지 정보 요청
activate D
D --> S : select address_no = {address_no}에 해당하는 유저 배송지 정보 응답
deactivate D
S --> C : static asset(HTML,CSS,JS) 응답
deactivate S
C --> U : 배송지 수정 모달 활성화
U -> C : 배송지 정보 수정 및 배송지 수정 완료 버튼 입력
C -> S : static asset(HTML,CSS,JS) 요청
activate S
S --> D : 배송지 추가 정보 전달
activate D
D --> S : select user_no = {user_no}에 해당하는 유저 배송지 목록 응답
deactivate D
S --> C : static asset(HTML,CSS,JS) 응답
deactivate S
C --> U : 배송지 수정 모달 비활성화 및 배송지 목록 출력
deactivate C

U -> C : 배송지 삭제 버튼 입력
activate C
C -> S : static asset(HTML,CSS,JS) 요청
activate S
S --> C : static asset(HTML,CSS,JS) 응답
deactivate S
C --> U : 배송지 삭제 모달 활성화
U -> C : 배송지 삭제 확인 버튼 입력
C -> S : static asset(HTML,CSS,JS) 요청
activate S
S -> D : 삭제할 배송지 정보 전달
activate D
D --> S : select user_no = {user_no}에 해당하는 유저 배송지 목록 응답
deactivate D
S --> C : static asset(HTML,CSS,JS) 응답
deactivate S
C --> U : 배송지 삭제 모달 비활성화 및 배송지 목록 출력
deactivate C
@enduml